### ISSUE TITLE
support paging3

### ISSUE THREAD

**Issue by BarryLius** [dokar3/LazyRecycler#137]
This library so cool !!!
Can paging3 be supported?

**Comment by dokar3** [comment]
Hi, there is currently no Paging3 support. The feature may be added as soon as I have time, it may take some time to investigate since I have left RecyclerView (also other Views) for a while.

**Comment by BarryLius** [comment]
> Hi, there is currently no Paging3 support. The feature may be added as soon as I have time, it may take some time to investigate since I have left RecyclerView (also other Views) for a while.

**Comment by dokar3** [comment]
A new release is out with Paging 3 support!
https://github.com/dokar3/LazyRecycler/releases/tag/v0.4.0
https://github.com/dokar3/LazyRecycler#paging-3
